#!/bin/sh

# This script runs when init it run during the boot process.
# Mounts everything in the fstab

mount -a
#mount -o remount +w /

#
# Mount the RAM filesystem to /tmp
#

mount -t ramfs -n none /tmp
mount -t ramfs -n none /var

export PATH=$PATH:/etc/ath

#insmod /lib/modules/2.6.15/net/ag7100_mod.ko
#insmod /lib/modules/2.6.15/net/ag7240_mod.ko

#
# Set lo eth1 up
#
ifconfig lo 127.0.0.1 up
#ifconfig eth1 up

#
# insert netfilter/iptables modules
#

/etc/init.d/rc.modules

#
# reset states of buttons
#
echo "set_btn_stats 0" > /dev/rtl8198_gpio

#
# set op mode to GATEWAY & disable VLANs
#
echo 0 > /proc/sw_nat
echo 0 > /proc/rtk_vlan_support
echo 2 > /proc/br_igmpVersion
echo 1 > /proc/br_igmpquery
echo 1 > /proc/br_igmpsnoop
echo 1,0 > /proc/br_mCastFastFwd

#
# Start Our Router Program
#

/usr/bin/httpd &

echo 524288 > /proc/sys/net/ipv4/ipfrag_high_thresh

#temporary way for smb memory fragment issue. Delete this after we have mempool in smb
echo 3 >/proc/sys/vm/dirty_background_ratio
echo 75 >/proc/sys/vm/dirty_ratio
echo 200 >/proc/sys/vm/vfs_cache_pressure
